# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# available runs-on are listed here:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners

on: ['workflow_dispatch', 'push', 'pull_request'] #hm, is there a better one?
# on... "publish" doesnt work?

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Build
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - name: Install and Build
        run: |
          yarn
          yarn build

      - name: Make artifacts dir
        run: mkdir -p artifacts

      - name: get_datetime
        id: get_datetime
        uses: mcgrue/get_datetime@master
        with:
          tz1: 'America'
          tz2: 'Los_Angeles'

      - name: Compress Ubuntu Artifact
        run: |
          zip -r artifacts/ubuntu-electon-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip ./electronbuild-output

      - name: Save Ubuntu Artifact
        uses: actions/upload-artifact@v3
        with:
          name: |
            ubuntu-electon-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip
          path: |
            artifacts/ubuntu-electon-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - name: Install and Build
        run: |
          yarn
          yarn build
          dir
          dir .\electronbuild-output\

      - name: Make artifacts dir
        run: if (Test-Path artifacts) {} else { mkdir artifacts }

      - name: get_datetime
        id: get_datetime
        uses: mcgrue/get_datetime@master
        with:
          tz1: 'America'
          tz2: 'Los_Angeles'

      - name: Compress Windows Artifact
        run: |
          Compress-Archive -DestinationPath .\artifacts\win-electron-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip -Path .\electronbuild-output\ -CompressionLevel Optimal

      - name: Check Artifact
        run: |
          dir .\artifacts\

      - name: Save Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: |
            win-electon-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip
          path: |
            artifacts/win-electron-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - name: Install and Build
        run: |
          yarn
          yarn build

      - name: Make artifacts dir
        run: mkdir -p artifacts

      - name: get_datetime
        id: get_datetime
        uses: mcgrue/get_datetime@master
        with:
          tz1: 'America'
          tz2: 'Los_Angeles'

      - name: Compresss MacOS Artifact
        run: |
          zip -r artifacts/macos-electron-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip ./electronbuild-output

      - name: Save MacOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: |
            macos-electron-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip
          path: |
            artifacts/macos-electron-${{ steps.get_datetime.outputs.datetime_str }}-${{ github.sha }}.zip
